name: Test Goose Recipe Shortener

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Test basic deep link generation without shortening
      - name: Test Deep Link Generation
        uses: aaalaniz/goose-recipe-shortener@main
        id: basic_test
        with:
          recipe_path: example-recipe.yaml

      # Verify the output exists
      - name: Verify Deep Link Output
        run: |
          if [ -z "${{ steps.basic_test.outputs.goose_deep_link }}" ]; then
            echo "Deep link was not generated"
            exit 1
          fi
          echo "Generated deep link: ${{ steps.basic_test.outputs.goose_deep_link }}"

      # Test Short.io link generation
      - name: Test Short.io Link Generation
        uses: aaalaniz/goose-recipe-shortener@main
        id: shortio_test
        with:
          recipe_path: example-recipe.yaml
          shortener: shortio
          short_url_path: example-recipe
          shortio_api_key: ${{ secrets.SHORTIO_API_KEY }}
          shortio_domain: ${{ secrets.SHORTIO_DOMAIN }}

      # Verify the Short.io link output exists
      - name: Verify Short.io Link Output
        run: |
          if [ -z "${{ steps.shortio_test.outputs.short_url }}" ]; then
            echo "Short.io link was not generated"
            exit 1
          fi
          echo "Generated Short.io link: ${{ steps.shortio_test.outputs.short_url }}"